services:
  - type: web
    name: dropzap
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3000"
      - key: HOSTNAME
        value: 0.0.0.0
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
